### ISSUE TITLE
请问该开源项目应用到具体什么项目上去了，能佛列举出来么？

### ISSUE THREAD

**Issue by achilsh** [xiongziliang/ZLToolKit#11]

**Comment by xiongziliang** [comment]
1、应用于ZLMediaKit(作者另外一个开源项目)，已经部署于商用服务器(包括网络摄像头项目、IPTV项目等)，目前运行状况稳定。
2、作者目前从事服务器开发，作者开发的项目基本都基于ZLToolKit开发，目前已经应用于多个商业项目。
3、linkingvision(rapidvms)用到了ZLMediaKit。
4、很多开发者用到了该项目，包括摄像头嵌入式服务器、温室大棚视频监控等项目，有蛮多开发者反馈正在使用。

**Comment by xiongziliang** [comment]
你可以加QQ群来讨论下，里面很多用户正在用，我经常能收到各种反馈，不过都是功能性的改进反馈，core dump这种反馈我还没收到过。
这个项目有着严格的线程安全隔离机制，并且使用智能指针避免内存错误问题，而且还经过大量的迭代改进和valgrind测试，所以你用这个做服务器开发完全没问题，我用这个做的服务器都是启动不管的那种

**Comment by xiongziliang** [comment]
ZLToolKit可能用户群体不是很多 但是ZLMediaKit用户还是蛮多的

**Comment by achilsh** [comment]
qq群是多少，方便贴出来么？

**Comment by xiongziliang** [comment]
> qq群是多少，方便贴出来么？

建议你看下项目主页README
