### ISSUE TITLE
error C3861: “asprintf”: 找不到标识符

### ISSUE THREAD

**Issue by lvshiling** [xiongziliang/ZLToolKit#12]

**Comment by lvshiling** [comment]
Microsoft Visual Studio Community 2017 
版本 15.8.8

Release,x64

**Comment by xiongziliang** [comment]
信息量不够，不足以定位问题 ，请把vs的错误提示完整的粘贴出来，谢谢

**Comment by lvshiling** [comment]
1>f:\babeframework\zltoolkit\src\util\sqlpool.h(127): note: 参见对正在编译的函数 模板 实例化“std::shared_ptr<toolkit::Timer> std::make_shared<toolkit::Timer,int,toolkit::SqlPool::{ctor}::<lambda_26611ed7bf806c6e05583146667402a9>,nullptr>(int &&,toolkit::SqlPool::{ctor}::<lambda_26611ed7bf806c6e05583146667402a9> &&,nullptr &&)”的引用
1>f:\babeframework\zltoolkit\src\util\sqlconnection.h(192): error C3861: “asprintf”: 找不到标识符
1>f:\babeframework\zltoolkit\src\util\sqlconnection.h(201): note: 参见对正在编译的函数 模板 实例化“std::string toolkit::SqlConnection::queryString<int&>(const char *,int &)”的引用
1>f:\babeframework\zltoolkit\src\util\sqlpool.h(86): note: 参见对正在编译的函数 模板 实例化“std::string toolkit::SqlConnection::queryString<int&>(const std::string &,int &)”的引用
1>f:\babeframework\zltoolkit\src\util\sqlpool.h(165): note: 参见对正在编译的函数 模板 实例化“void toolkit::SqlPool::asyncQuery<std::string&,int&>(std::string &,int &)”的引用

**Comment by xiongziliang** [comment]
你如果暂时用不到mysql数据库连接池 可以先把 srs/Util/sqlconnection.cpp srs/Util/sqlconnection.h srs/Util/sqlpool.h 删除

那个 找不到asprintf的编译问题应该是头文件未添加齐全的问题 我还要在windows上编译一遍才能解决，要等一会

**Comment by dosmlp** [comment]
我在Windows下也遇到这个问题，不过，格式化库能不能用这个https://github.com/fmtlib/fmt

**Comment by xiongziliang** [comment]
您好 这个问题已经修复了 请查看最新提交，感情您对本项目的支持，谢谢！
