### ISSUE TITLE
当我退出进程后遇到这些打印的问题

### ISSUE THREAD

**Issue by dqiang** [xiongziliang/ZLToolKit#16]
Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

Exception at 0x75264592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\kitlib\poller\eventpoller.cpp:87

目前不知道该原因是什么意思

**Comment by xiongziliang** [comment]
你是vs调试模式吧？没关系的，EventPoller线程是通过抛异常的方式控制退出，vs捕获了这个异常而已：
![image](https://user-images.githubusercontent.com/11495632/67074924-bab3c500-f1bc-11e9-8070-5ece7bfcc0fe.png)
