### ISSUE TITLE
_sessionMap 一致性问题？

### ISSUE THREAD

**Issue by sjd3211888** [xiongziliang/ZLToolKit#18]
void onManagerSession() {
		for (auto &pr : _sessionMap) {
			weak_ptr<TcpSession> weakSession = pr.second->session();
			pr.second->session()->async([weakSession]() {
				auto strongSession=weakSession.lock();
				if(!strongSession) {
					return;
				}
				strongSession->onManager();
			}, false);
		}
	}

请问 在处理这个sessionmap的时候 我卡你这个时候遍历 还是这个seessionmap的添加删除 都没用锁，如果这个seesion遍历的过程中，map被添加或者删除了怎么办，这个是怎么保持一致性的？每太搞明白

**Comment by sjd3211888** [comment]
额  好像是通过一个线程实现的的？一个poller内处理的？

**Comment by xiongziliang** [comment]
每个TCPServer 实例以及它下面的所有TCPSession都是单线程的，它的onAccept，onErr、onRead、定时器事件都在一个线程中触发，所有不需要互斥锁
