### ISSUE TITLE
qml c++异常错误

### ISSUE THREAD

**Issue by dqiang** [xiongziliang/ZLToolKit#19]
qml 里面只要 Socket::Ptr sockRecv(new Socket());//创建一个UDP端口，然后关闭程序会报这样的错误
Exception at 0x743e4592, code: 0xe06d7363: C++ exception, flags=0x1 (execution cannot be continued) (first chance) at e:\xxxx\poller\eventpoller.cpp:87

**Comment by xiongziliang** [comment]
我不是已经答复你了吗？#16
