### ISSUE TITLE
test_tcpClient如何错误重连

### ISSUE THREAD

**Issue by airx** [xiongziliang/ZLToolKit#2]
比如服务器端口关闭，或者客户端断网等情况，如何在test_tcpClient中实现断线重连呢

**Comment by xiongziliang** [comment]
你可以在onErr重载函数里面实现重连，建议延时重连

**Comment by airx** [comment]
这样的：
virtual void onErr(const SockException &ex) override{
		//断开连接事件，一般是EOF
		WarnL << ex.what();
		_timer.reset();
		connect();
	}
但是却没有再进入onConnect回调函数了，是为什么？需要重启loop？

**Comment by xiongziliang** [comment]
连接不是startConnect方法吗？哪来的connect方法？

**Comment by airx** [comment]
public:
	typedef std::shared_ptr<TestClient> Ptr;
	TestClient() {
	}
	virtual ~TestClient(){}
	void connect(){
		//这里改成实际服务器地址
		startConnect("10.0.0.50",9000);
	}

**Comment by airx** [comment]
不管是connect还是startConnect，调用后，都没有onConnect的回调

**Comment by xiongziliang** [comment]
我刚才测试了下，断开重连逻辑不能同步放在onErr重载函数里面持续；因为在触发onErr函数后还有一些清理工作要做，此时你立即发起重连会被随后的清理工作清除掉，所以保险的做法是延时重连，而且延时重连是通行的做法，断线后立即重连也是不科学的

**Comment by xiongziliang** [comment]
我刚才测试了下，断开重连逻辑不能同步放在onErr重载函数里面执行；因为在触发onErr函数后还有一些清理工作要做，此时你立即发起重连会被随后的清理工作清除掉，所以保险的做法是延时重连，而且延时重连是通行的做法，断线后立即重连也是不科学的

**Comment by airx** [comment]
virtual void onErr(const SockException &ex) override{
		//断开连接事件，一般是EOF
		WarnL << ex.what();
		_timer.reset();
		sleep(10);
		connect();
}
貌似这样写也是不行的，会阻塞主线程？应该开个定时器？

**Comment by xiongziliang** [comment]
不能这样写，建议你用一个Timer做延时重连。我马上提交下代码，可以实现立即重连 但是还是不建议你立即重连。test_tcpClient和test_tcpEchoServer现在也加入断开重连代码，你可以等我提交代码后再测试下 我这边测试通过了

**Comment by xiongziliang** [comment]
代码已经提交了，你测试通过了回复我

**Comment by airx** [comment]
现在确实是立即重连，不过只有一次。
不过我想达到的效果是，一直保持重连，除非连上了，有个这种API开关比较好，或者该怎么写比较好？
我们也是为了上层开发省力，麻烦了

**Comment by xiongziliang** [comment]
那个你可以用Timer去一直尝试延时重连，你可以参考我另外一个项目代码，具体是ZLMediaKit/src/Device/PlayerProxy.cpp,里面有延时不断重连的代码实现。不断重连这种业务逻辑还是要你自己来写

**Comment by airx** [comment]
<img width="584" alt="qq20171130-162852 2x" src="https://user-images.githubusercontent.com/1214492/33420991-93a9e5aa-d5eb-11e7-803f-cc384b07e996.png">
你看下这样写timer有没问题，比如内存泄露什么的？

**Comment by xiongziliang** [comment]
嗯 没什么问题 ，应该不会有内存泄露的问题。你实现断线重连机制的关键就是连接失败或断开连接后开辟定时器一直重连，重连成功了就取消重连定时器。看你这个代码应该没问题

**Comment by airx** [comment]
嗯，再问一个问题，如果我想在onErr里面退出事件循环，是直接调用EventPoller::Destory()吗

**Comment by xiongziliang** [comment]
不是 应该调用EventPoller::Instance().shutdown方法 但是强烈不建议你这么做 。你这样做的结果就跟程序退出没什么区别

**Comment by airx** [comment]
问一下仁兄，这个库的稳定性如何，有用在什么项目里经过时间检验吗？我是打算把这个用在各平台的客户端上。

**Comment by xiongziliang** [comment]
我用这个toolkit做的一个tcp转发服务器模拟12万用户同时在线 连续测试了3天 没有任何问题，那个服务器现在启动了140多天 一直没重启过，上面一直也是有业务量的。基于toolkit的我另外一个开源项目mediakit在我们公司长达半年的使用测试中都表现的极奇稳定，我们连续不断的高强度自动测试了3个月，表现让人满意。我们公司的ios播放器,嵌入式设备，服务器都是基于这两个库的，我们的服务器一启动服务就是按月来算，除了更新代码重来没自动启动过。我平常都不用看门狗脚本的
