### ISSUE TITLE
关于 sqlpool

### ISSUE THREAD

**Issue by sjd3211888** [xiongziliang/ZLToolKit#23]
请问下 这个数据库的轮子可以弄成多实例的么 就可以连接几个IP 几个Database的那种

**Comment by xiongziliang** [comment]
很遗憾不太行，现在是用单例实现的，要改成支持多个IP的数据库，那么之前的API改动会比较大(而且不会有像现在cout那样使用简单)，目前我也没这个需求，如果你有这个需求，你可以尝试自己修改下代码。
