### ISSUE TITLE
Socket类里的_mtx_socket问题

### ISSUE THREAD

**Issue by hankai17** [xiongziliang/ZLToolKit#26]
正在分析作者的网络库 对Socket的成员_mtx_socket很疑惑
TcpServer.h中
```
virtual Socket::Ptr onBeforeAcceptConnection(const EventPoller::Ptr &poller){
        /**
         * 服务器器模型socket是线程安全的，所以为了提高性能，关闭互斥锁
         */
        return std::make_shared<Socket>(poller,false);
    }
```
服务器模型是线程安全的 因为socket的读/写/超时/关闭 都是在一个线程中顺序执行的 不需要互斥量 所以为了提高性能 关闭互斥锁
那么非服务器模型 为什么线程不安全的呢? 具体而言就是
```
commit a549490e Jzan <jzan@192.168.0.121> on 3/5/17 at 6:20 PM
```
是基于什么场景呢?

**Comment by xiongziliang** [comment]
服务器跟客户端还是区别很多的。
客户端是用户驱动模式，也就是用户控制什么时候触发网络发送事件，比如说用户登录登出、播放器停止开始、拖动进度条等。
这些操作都是UI线程驱动的，那么势必存在UI线程、网络线程同时操作socket和它对应的对象。那么这个时候一般有两种做法：
- 1、UI线程触发的事件放到网络线程中去触发，那么这就涉及到线程切换。
- 2、对对象和资源上锁。


第一种方式只适合那种对操作返回值不敏感或低频度的操作，所以在客户端上锁是一种可选项了。


而服务器不同，服务器是网络事件驱动模型，里面的事件一般无非两种，一种是网络IO事件，一种是定时器事件，这些事件都是同一个线程触发的。

如果存在一个线程操作另外一个线程下的对象这种情况(比如说即时聊天的应用场景)，那么一般用线程切换来解决这个问题，那么这样下来，服务器是可以做到无锁的。
