### ISSUE TITLE
TCP半包，粘包与分包的问题

### ISSUE THREAD

**Issue by airx** [xiongziliang/ZLToolKit#3]
onRecv方法，如何处理TCP的半包，粘包与分包的问题呢

**Comment by xiongziliang** [comment]
tcp是流协议，亦即源源不断的数据流，它不像udp一样有明显的数据包概念；所以粘包现象是正常的，处理粘包现象是应用层协议，有两种解决方案，一种是分隔符号方案，这种方案性能太差，不推荐；另外一种是指定包长度方案，这个是主流的方案；http 协议中的content-length字段也是第二种方案的表现；而http get命令中却是通过两个连续的回车符来做数据包分隔的，所以http协议两种方案都用了

**Comment by airx** [comment]
那看来得自己维护一个buffer，因为Socket::Buffer是固定的一块内存。
比如这次onRecv方法里只有100字节，而我需要145字节，我就得等下次到了45字节再一起处理；也有可能下次到了80字节，还得把剩下35字节留着下次解析。

**Comment by xiongziliang** [comment]
对 你用个string缓存处理下
