### ISSUE TITLE
Windows下关于 g_defaultLogger 的编译问题

### ISSUE THREAD

**Issue by yantanglife** [xiongziliang/ZLToolKit#30]
VS2017，到编译 ALL_BUILD 时，出现如下问题：
> test_logger.obj : error LNK2019: 无法解析的外部符号 "class toolkit::Logger * toolkit::g_defaultLogger" (?g_defaultLogger@toolkit@@3PAVLogger@1@A)，该符号在函数 _main 中被引用

> test_delayTask.obj : error LNK2019: 无法解析的外部符号 "class toolkit::Logger * toolkit::g_defaultLogger" (?g_defaultLogger@toolkit@@3PAVLogger@1@A)，该符号在函数 "private: virtual void __thiscall std::_Func_impl_no_alloc<class <lambda_1f860e808c4732d9497d62aaa8d648d8>,void>::_Do_call(void)" (?_Do_call@?$_Func_impl_no_alloc@V<lambda_1f860e808c4732d9497d62aaa8d648d8>@@X$$V@std@@EAEXXZ) 中被引用

> ...

请问是test项目的引用有问题吗

**Comment by yantanglife** [comment]
问题找到了。与 g_defaultLogger 的 extern 声明有关。
g_defaultLogger 的定义在 Logger.cpp 中，在 test 项目中，如果加上 g_defaultLogger 的定义 `Logger* g_defaultLogger = &Logger::Instance();`，就不会出现“无法解析的外部符号”错误。另外要改变`lambda 的捕获方式。
你在windows下测试的时候没有遇到这个问题吗？难道是我 VS 的设置问题？

**Comment by xiongziliang** [comment]
这个问题之前有人反馈过 不过重新cmake后接近了

**Comment by yantanglife** [comment]
好吧，我也重新 cmake 过...但是并没有什么变化

**Comment by daiminghuan** [comment]
> VS2017，到编译 ALL_BUILD 时，出现如下问题：
> 
> > test_logger.obj : error LNK2019: 无法解析的外部符号 "class toolkit::Logger * toolkit::g_defaultLogger" (?g_defaultLogger@toolkit@@3PAVLogger@1@A)，该符号在函数 _main 中被引用
> 
> > test_delayTask.obj : error LNK2019: 无法解析的外部符号 "class toolkit::Logger * toolkit::g_defaultLogger" (?g_defaultLogger@toolkit@@3PAVLogger@1@A)，该符号在函数 "private: virtual void __thiscall std::_Func_impl_no_alloc<class <lambda_1f860e808c4732d9497d62aaa8d648d8>,void>::_Do_call(void)" (?_Do_call@?$_Func_impl_no_alloc@V<lambda_1f860e808c4732d9497d62aaa8d648d8>@@x$$V@std@@EAEXXZ) 中被引用
> 
> > ...
> 
> 请问是test项目的引用有问题吗

老哥 你这个咋解决了啊， 我也是一样的无法解析

**Comment by xia-chu** [comment]
> 问题找到了。与 g_defaultLogger 的 extern 声明有关。
> g_defaultLogger 的定义在 Logger.cpp 中，在 test 项目中，如果加上 g_defaultLogger 的定义 `Logger* g_defaultLogger = &Logger::Instance();`，就不会出现“无法解析的外部符号”错误。另外要改变`lambda 的捕获方式。
> 你在windows下测试的时候没有遇到这个问题吗？难道是我 VS 的设置问题？

@daiminghuan 这个不是说了吗
