### ISSUE TITLE
关于ThreadLoadCounter统计问题

### ISSUE THREAD

**Issue by lam2003** [xiongziliang/ZLToolKit#32]
`  
ThreadPool(int num = 1,
               Priority priority = PRIORITY_HIGHEST,
               bool autoRun = true) ;
`

ThreadPool允许创建多条线程. 在ThreadPool::run()中调用startSleep()与sleepWakeUp()进行load统计,当线程数大于1时,load统计是否不准确?

**Comment by lam2003** [comment]
`    void run() {
        ThreadPool::setPriority(_priority);
        Task::Ptr task;
        while (true) {
            startSleep();
            if (!_queue.get_task(task)) {
                //空任务，退出线程
                break;
            }
            sleepWakeUp();
            try {
                (*task)();
                task = nullptr;
            } catch (std::exception &ex) {
                ErrorL << "ThreadPool执行任务捕获到异常:" << ex.what();
            }
        }
    }`

**Comment by xiongziliang** [comment]
准确的 这个是成员方法 而不是类方法

**Comment by lam2003** [comment]
是成员方法, 但多条线程都在执行同一个ThreadPool对象的run函数?这没有影响吗

**Comment by xiongziliang** [comment]
> 是成员方法, 但多条线程都在执行同一个ThreadPool对象的run函数?这没有影响吗

既然是成员方法，那么成员变量互相隔离的，当然不影响啊。本质上所有成员方法都不属于类的一部分，成员方法只是比类方法多个this指针参数，通过this指针来做数据隔离的，所以多线程执行同一个方法，只要数据是隔离的，都是安全的

**Comment by lam2003** [comment]
我纠结的不是成员不成员方法这一点，我纠结的时你这个loadcounter设计的时候有考虑多线程共用一个counter的情况吗？还是说要给每条线程提供一个loadcounter，最终的load(平均值)通过 所有loadcounter的load累加/loadcounter数量 来计算

**Comment by lam2003** [comment]
比如你有两条线程共用一个loadcounter，时序图如下
              sleep                  t1                 wakeup
thread1     |--------------------------------------|
              sleep  t2   wakeup  t3  sleep t4
thread2     |-------------|----------------|--------|

假设线程thread1 thtread2都总共运行时长是t1

counter的load等于 t3 / t1
但实际上是 t3 / 2*t1

**Comment by xiongziliang** [comment]
loadcounter也不存在多条线程访问的问题啊

**Comment by xiongziliang** [comment]
一条线程操作一个ThreadPool对象，每个ThreadPool对象继承于loadcounter啊

**Comment by lam2003** [comment]
一条线程操作一个ThreadPool对象是确实没问题，但我看你的ThreadPool构造函数是运行创建多条线程的，如果ThreadPool只有一条线程，为何不叫Worker

**Comment by xiongziliang** [comment]
> 一条线程操作一个ThreadPool对象是确实没问题，但我看你的ThreadPool构造函数是允许创建多条线程的，如果ThreadPool只有一条线程，为何不叫Worker

哦哦， 由于历史原因啊，很早前确实是ThreadPool，后面改成了你所谓的Worker，现在直接没用到了。

**Comment by xiongziliang** [comment]
我本来是的打算删除这个代码的，但是有人让我别删除，所以就保留在这里了
