### ISSUE TITLE
请教TCP拆包和粘包的处理解决办法

### ISSUE THREAD

**Issue by lixinhan2019** [xiongziliang/ZLToolKit#33]
我仔细看了您流媒体服务器中HTTP中关于TCP合包的代码,但是无论才疏学浅,没有很明白,希望作者可以大概讲解下TCP处理拆包粘包的思路,现在基于ZLToolKit要实现一个大文件收发,出现拆包粘包问题.
另外我现在需要实现http上传文件,您的http里面有实现好的吗?或者告诉我一个解决思路,非常感谢

**Comment by xiongziliang** [comment]
http是混合制拆包，http头是根据分隔符分包`\r\n\r\n`。
content-body 是二进制，根据包长度分隔`content-length`.

**Comment by xiongziliang** [comment]
一般采用指定包长度来解决粘包问题

**Comment by lixinhan2019** [comment]
好的,明白了,那http上传文件呢?

**Comment by xiongziliang** [comment]
不一样吗?

**Comment by lixinhan2019** [comment]
我看你http POST提交请求例子这样写的
//创建一个Http请求器
    HttpRequester::Ptr requesterPost(new HttpRequester());
    //使用POST方式请求
    requesterPost->setMethod("POST");
    //设置http请求头
    requesterPost->addHeader("X-Requested-With", "XMLHttpRequest");
    requesterPost->addHeader("Origin", "http://fanyi.baidu.com");
    //设置POST参数列表
    HttpArgs args;
    args["query"] = "test";
    args["from"] = "en";
    args["to"] = "zh";
    args["transtype"] = "translang";
    args["simple_means_flag"] = "3";
    requesterPost->setBody(args.make());
    //开启请求
    requesterPost->startRequester("http://fanyi.baidu.com/langdetect",//url地址

表单用HttpArgs 提交,那如果是上传文件,文件流应该在哪追加呢?

**Comment by xiongziliang** [comment]
你可以用HttpFileBody或HttpMultiFormBody对象上传文件

**Comment by lixinhan2019** [comment]
好的,多谢指导
