### ISSUE TITLE
copy ctor 也不 = delete ，还敢在头文件里定义虚拟析构？

### ISSUE THREAD

**Issue by lhmouse** [xiongziliang/ZLToolKit#8]
https://github.com/xiongziliang/ZLToolKit/blob/7353a131b46ab6af46d9de23078076d1932f33fb/src/Thread/rwmutex.h#L74

**Comment by xiongziliang** [comment]
这个代码是实验性质的 其实并没用到 接口写的也不是那么万全

**Comment by xiongziliang** [comment]
虚析构函数只是我个人的一个编程习惯而已

**Comment by FrankHB** [comment]
什么渣渣标题，多提两个 issue 会死？

@xiongziliang 你大概理解错了，后面半句单独是两个工程缺陷。
在你习惯之外最好习惯`-Werror=weak-vtables`。

**Comment by xiongziliang** [comment]
@FrankHB 谢谢指导
