### ISSUE TITLE
这年头怎么是个人就敢写自旋锁了？

### ISSUE THREAD

**Issue by lhmouse** [xiongziliang/ZLToolKit#9]
https://github.com/xiongziliang/ZLToolKit/blob/7353a131b46ab6af46d9de23078076d1932f33fb/src/Thread/spin_mutex.h#L44

且不说用户态根本无法屏蔽 context switch， 就你这渣渣实现，和 [其它实现](https://github.com/lhmouse/mcfgthread/blob/master/src/env/mutex.c?ts=4#L85) 比较过吗？ 有做过 [性能测试](https://github.com/lhmouse/mcfgthread/wiki/Benchmarking) 吗？

**Comment by FrankHB** [comment]
没说非得用户态吧……而且吱实现不是IA-32就趴了，完败（
比较起来更好奇“娣诲姞鐩爣鏂囦欢 ”那个commit msg是smg。
xsk

**Comment by xiongziliang** [comment]
这个自旋锁不是我写的 我只是拿来主义用用而已

**Comment by xiongziliang** [comment]
你提的这些issue没有任何建设性

**Comment by FrankHB** [comment]
@xiongziliang 不地道啊，“Copyright (c) ”后面挂名不是你么。

**Comment by lhmouse** [comment]
“建设性”呵，四处炸 s@#t 连基本的语义正确都无法保证，还有碧莲遑论“建设性”？

**Comment by xiongziliang** [comment]
@lhmouse 我觉得你应该好好学习下交流的基本礼貌再来说话 你上来一就骂人是建设性的？

**Comment by lhmouse** [comment]
我哪骂人了？

**Comment by xiongziliang** [comment]
碧莲 SB

**Comment by FrankHB** [comment]
@xiongziliang 如果实际上不存在授权，那么基本就构成侵权了。虽然要是一开始注明出处倒还能考虑合理使用条款救一救。

**Comment by lhmouse** [comment]
这也叫骂人蛤蛤蛤…… @FrankHB

**Comment by zhllxt** [comment]
> https://github.com/xiongziliang/ZLToolKit/blob/7353a131b46ab6af46d9de23078076d1932f33fb/src/Thread/spin_mutex.h#L44
> 
> 且不说用户态根本无法屏蔽 context switch， 就你这渣渣实现，和 [其它实现](https://github.com/lhmouse/mcfgthread/blob/master/src/env/mutex.c?ts=4#L85) 比较过吗？ 有做过 [性能测试](https://github.com/lhmouse/mcfgthread/wiki/Benchmarking) 吗？

这个自旋锁是boost库里面的实现。只不过这个作者稍稍改动了一下。搞人身攻击不太好。

**Comment by xia-chu** [comment]
我是网上看见的 我不是作者



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhllxt <notifications@github.com&gt;
发送时间: 2020年10月14日 16:36
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 这年头怎么是个人就敢写自旋锁了？ (#9)





  
https://github.com/xiongziliang/ZLToolKit/blob/7353a131b46ab6af46d9de23078076d1932f33fb/src/Thread/spin_mutex.h#L44
 
且不说用户态根本无法屏蔽 context switch， 就你这渣渣实现，和 其它实现 比较过吗？ 有做过 性能测试 吗？
  
这个自旋锁是boost库里面的实现。只不过这个作者稍稍改动了一下。搞人身攻击不太好。

**Comment by xia-chu** [comment]
现在也删除这个代码了 pthread里面也会自旋



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhllxt <notifications@github.com&gt;
发送时间: 2020年10月14日 16:36
收件人: xia-chu/ZLToolKit <ZLToolKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLToolKit] 这年头怎么是个人就敢写自旋锁了？ (#9)





  
https://github.com/xiongziliang/ZLToolKit/blob/7353a131b46ab6af46d9de23078076d1932f33fb/src/Thread/spin_mutex.h#L44
 
且不说用户态根本无法屏蔽 context switch， 就你这渣渣实现，和 其它实现 比较过吗？ 有做过 性能测试 吗？
  
这个自旋锁是boost库里面的实现。只不过这个作者稍稍改动了一下。搞人身攻击不太好。
